export const SOCKET_EVENTS = {
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  STOP: 'STOP',
  QUEUE_UPDATED: 'QUEUE_UPDATED',
  VOLUME: 'VOLUME',
  GROUPS_UPDATED: 'GROUPS_UPDATED',
} as const;
